create database d_g;

#use d_g;

CREATE TABLE Twitter_search(
	TWITTER_QUERY VARCHAR (25) NOT NULL,
    RESULT_ID INT (20) NOT NULL,
    POSITION INT (20) NOT NULL,
    RATING INT (20) NOT NULL,
    NOTES VARCHAR (25) NOT NULL
    );
    
INSERT INTO Twitter_search(TWITTER_QUERY,RESULT_ID, POSITION,RATING,NOTES) VALUES ('dog',1000,1,2,'Picture of Snoog dog');
INSERT INTO Twitter_search(TWITTER_QUERY,RESULT_ID, POSITION,RATING,NOTES) VALUES ('dog',998,2,4,'Dog Walking');
INSERT INTO Twitter_search(TWITTER_QUERY,RESULT_ID, POSITION,RATING,NOTES) VALUES ('dog',342,3,1,'Donkey');
INSERT INTO Twitter_search(TWITTER_QUERY,RESULT_ID, POSITION,RATING,NOTES) VALUES ('cat',123,1,4,'Picture of cat');
INSERT INTO Twitter_search(TWITTER_QUERY,RESULT_ID, POSITION,RATING,NOTES) VALUES ('cat',435,2,2,'Cat memes');
INSERT INTO Twitter_search(TWITTER_QUERY,RESULT_ID, POSITION,RATING,NOTES) VALUES ('cat',545,3,1,'Burrito');

SELECT 
	TWITTER_QUERY,
    RESULT_ID, 
    POSITION,
    RATING,
    NOTES,
    CASE 
        WHEN ((10-POSITION)+RATING) > 11 THEN 'REALATED' 
        WHEN ((10-POSITION)+RATING) < 10 THEN 'UNRELATED' 
        ELSE 'RELATABLE' 
    END as 'Search Rating'
     
    FROM Twitter_search
    ;

